# .github/workflows/deploy-frontend.yml
name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you're using

      - name: Install dependencies
        working-directory: ./frontend  # Navigate to the frontend folder
        run: |
          npm install  # Install dependencies using npm

      - name: Build React app
        working-directory: ./frontend  # Navigate to the frontend folder
        run: |
          npm run build  # Build the React app for production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Azure Static Web Apps token secret
          repository: ${{ github.repository }}
          branch: main
          app_location: "/frontend"  # Location of the React app (frontend folder)
          api_location: "/backend"  # Optional: If you want to deploy the API along with the frontend
          output_location: "/frontend/build"  # The build output folder of the React app
