on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: taxi-fare-prediction
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.9.0'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies, build, and test (Frontend)
      run: |
        npm install                # Install the dependencies in frontend
        npm run build --if-present  # Build the frontend project (if applicable)
        npm run test --if-present   # Run tests (if applicable)
      env:
          CI: true  # Ensure Jest runs in CI mode
          
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: frontend-app

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: frontend-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
